apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kafka-topics-ui.fullname" . }}
  labels:
    app: {{ template "kafka-topics-ui.name" . }}
    chart: {{ template "kafka-topics-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kafka-topics-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kafka-topics-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "kafka-topics-ui.name" . }}-server
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: rest-proxy
              containerPort: {{ .Values.servicePort }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          - name: KAFKA_REST_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_REST_PROXY_URL
            value: "http://{{ template "kafka-topics-ui.kafka-rest.service-name" . }}"
          - name: PROXY
            value: "true"
          {{- range $key, $value := .Values.configurationOverrides }}
          - name: {{ printf $key | replace "." "_" | upper | quote }}
            value: {{ $value | quote }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
